apiVersion: v1
kind: Secret
metadata:
  name: openshift-controller-manager
data:
  kubeconfig: {{ pki "secret" "service-network-admin-kubeconfig" "kubeconfig"}}
  server.crt: {{ pki "secret" "openshift-controller-manager-cert" "tls.crt" }}
  server.key: {{ pki "secret" "openshift-controller-manager-cert" "tls.key" }}
