apiVersion: v1
kind: ConfigMap
metadata:
  name: openshift-oauth-apiserver
data:
  etcd-ca.crt: |-
{{ include_pki "secret" "root-ca" "ca.crt" 4 }}
  serving-ca.crt: |-
{{ include_pki "secret" "root-ca" "ca.crt" 4 }}
