apiVersion: v1
kind: Secret
metadata:
  name: openshift-oauth-apiserver
data:
  kubeconfig: {{ pki "secret" "service-network-admin-kubeconfig" "kubeconfig" }}
  server.crt: {{ pki "secret" "openshift-oauth-apiserver-cert" "tls.crt" }}
  server.key: {{ pki "secret" "openshift-oauth-apiserver-cert" "tls.key" }}
  etcd-client.crt: {{ pki "secret" "etcd-client-tls" "etcd-client.crt" }}
  etcd-client.key: {{ pki "secret" "etcd-client-tls" "etcd-client.key" }}
