apiVersion: v1
kind: Secret
metadata:
  name: metrics-proxy-certs
  labels:
    app: cluster-version-operator
    k8s-app: cluster-version-operator
type: kubernetes.io/tls
data:
  tls.crt: ""  # Will be populated by cert-manager or manual process
  tls.key: ""  # Will be populated by cert-manager or manual process
