apiVersion: v1
kind: Service
metadata:
  labels:
    app: cluster-version-operator
    k8s-app: cluster-version-operator
  name: cluster-version-operator
spec:
  ipFamilyPolicy: PreferDualStack
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  - name: metrics-proxy
    port: 8444
    protocol: TCP
    targetPort: metrics-proxy
  selector:
    app: cluster-version-operator
    k8s-app: cluster-version-operator
  type: ClusterIP
