apiVersion: v1
kind: Secret
metadata:
  name: default-ingress-cert
  namespace: openshift-ingress
data:
  tls.crt: {{ pki "secret" "ingress-crt" "tls.crt" }}
  tls.key: {{ pki "secret" "ingress-crt" "tls.key" }}
