apiVersion: v1
kind: Secret
metadata:
  name: oauth-openshift
data:
  kubeconfig: {{ pki "secret" "service-network-admin-kubeconfig" "kubeconfig" }}
  server.crt: {{ pki "secret" "ingress-crt" "tls.crt" }}
  server.key: {{ pki "secret" "ingress-crt" "tls.key" }}
